- name: Roboshop Frontend playbook
  host: all
  become: true
  tasks:
    - name: Install Nginx service
      ansible.builtin.yum:
        name: nginx
        state: installed
    
    - name: Start and Enable Nginx service
      anisble.builtin.systemd_service:
        name: nginx
        state: restart