---
- name: Mongodb Setup
  hosts: all
  become: true
  tasks:
    - name:  Copy Mongodb repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install Mongodb
      ansible.builtin.yum:
        name: mongodb-org
        state: installed

    - name: Replace localhost to 
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start and Enable Nginx service
      ansible.builtin.systemd_service:
        name: mongod
        state: restarted